services:
  webhook:
    build: .
    read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT}:8080"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CONFIG_FILE=/app/config.json
      - REDIS_HOST=${REDIS_HOST:-host.docker.internal}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - PORT=8080
      - WEBHOOK_USERNAME=${WEBHOOK_USERNAME:-}
      - WEBHOOK_PASSWORD=${WEBHOOK_PASSWORD:-}
    volumes:
      - ./config.json:/app/config.json:ro
    restart: on-failure:10
